### ISSUE TITLE
Add ability to see currently running tests in the results list

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#100]

**Comment by Workshop2** [comment]
@hemdagem @yetanotherchris - I think this would be handy if lots of builds are being run at the same time?

**Comment by Workshop2** [comment]
@hemdagem @yetanotherchris - maybe we could have a separate page just for running tests? Would probably be quicker to build and easier to maintain?

**Comment by yetanotherchris** [comment]
I think this should be a feature, but not for now - we need to think of feature cycles and stick that into the next one, or the one after.
