### ISSUE TITLE
I would like paging for the results pages

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#104]
We also need to speed these pages up

**Comment by hemdagem** [comment]
Awaiting #110 to be resolved

**Comment by yetanotherchris** [comment]
I get this error when I tried 25 results:

    Executor error: Overflow sort stage buffered data usage of 33704095 
    bytes exceeds internal limit of 33554432 bytes

http://stackoverflow.com/questions/27023622/overflow-sort-stage-buffered-data-usage-exceeds-internal-limit

**Comment by yetanotherchris** [comment]
Verified! :gem: :gem:

Also see 338cd342b9d4574f39b345555a9956b013e57589 (bug with in-memory sorting limits)
