### ISSUE TITLE
{capturedvariableXYZ} - rename these and update the view

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#112]
{capturedvariableXYZ} is a bit confusing - maybe have {_XYZ} for captured variables, or just keep the variable names the same as their description.

Also update the edit view so it displays AllAvailableVariables correctly

**Comment by Workshop2** [comment]
I like the idea of a prefix.

_
$
*

**Comment by Workshop2** [comment]
I would also like to see what variables were caught during the test run

**Comment by yetanotherchris** [comment]
In the log n00b

On Mon, 16 May 2016, 08:30 Simon C, <notifications@github.com> wrote:

> I would also like to see what variables were caught during the test run
>
> —
> You are receiving this because you authored the thread.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/TotalJobsGroup/Syringe/issues/112#issuecomment-219366072>
>
-- 

Sent from my Android

**Comment by Workshop2** [comment]
Confirmed
