### ISSUE TITLE
I want to be able to use shared scripts/C# snippets

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#131]
I would like to have a folder called "shared-scripts" that syringe looks for, and displays as a drop down list in each test under the Scripts section.

These would be .txt or .cs files with common re-usable scripts.

These would be added to the test XML, and use at run time.

**Comment by Workshop2** [comment]
We need this before wide usage at tjg.

Talking to @yetanotherchris we think we should have a `variable.json` file that is just a keyvalue list

**Comment by yetanotherchris** [comment]
Implemented in pull request #200
