### ISSUE TITLE
Unable to run tests that use captured variables in query string

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#139]
I would like to use a captured variable form a previous step to be used in the url for the next step.

For some reason the test runner tries to build the url for the second step in the 1st step. See the test case here: [Syringe Test Suite.json.txt](https://github.com/TotalJobsGroup/Syringe/files/265742/Syringe.Test.Suite.json.txt)

![bug](https://cloud.githubusercontent.com/assets/1476513/15283370/d56ce6ba-1b41-11e6-96d9-473468c94168.png)

**Comment by yetanotherchris** [comment]
The format is {capturedvariableNAME}

**Comment by Workshop2** [comment]
I thought something had changed as the suggestion at the top of the page said to just use `{new-test-file-url}`. This doesn't solve the issue of errors being reported in the wrong steps
