### ISSUE TITLE
Running a test case doesn't give me the same options as viewing results

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#147]
I would like to have to same features once a test has finished running as viewing a test e.g. `View Log`, `View HTTP Log` etc

**Comment by Workshop2** [comment]
I find myself jumping between views to get the information I need to debug issues...not a great user experience

**Comment by Workshop2** [comment]
@hemdagem @yetanotherchris - this would be a nice (and maybe easy feature) - anyone mind doing it soon?

**Comment by hemdagem** [comment]
@Workshop2 I think at the moment the results get saved at the end of the entire run so we won't have access to view the logs until it's finished running. Unless we update mongo as we finish each test, though not sure what the performance impact will be.

**Comment by Workshop2** [comment]
Unless we automatically redirect to that page once it has completed, that would probably be more useful?
