### ISSUE TITLE
I want to run all test files

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#166]
- Have a button
- Work from a rest call
- Return collective status

**Comment by Workshop2** [comment]
@yetanotherchris @hemdagem - how do we see this working? I think Neil suggested that you call into Syringe from Octopus to run all tests, but I would have thought we would just run the test file for that app/user flow that is getting deployed?

Maybe we need a way of grouping (or tagging) tests so you can run only the relevant tests?

**Comment by yetanotherchris** [comment]
$object = Invoke-RestRequest $url

	if ($object.Success)
	{

	}

**Comment by Workshop2** [comment]
@yetanotherchris - huh?

**Comment by syringe-integrationtests** [comment]
Huh?

**Comment by yetanotherchris** [comment]
Yes you'd run the test file, it only takes 2 seconds to run! You give it a URL as above and you get json back as an object

**Comment by yetanotherchris** [comment]
Add it as a future feature
