### ISSUE TITLE
Move from materialize to Bootstrap and Bootswatch

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#178]

**Comment by Workshop2** [comment]
There a loads of pages that look kinda broken or not right. I would prefer these to be looked into before resolving this issue

**Comment by Workshop2** [comment]
Thanks @irmbrady

**Comment by yetanotherchris** [comment]
Can we close this

**Comment by hemdagem** [comment]
Yes!
