### ISSUE TITLE
Signalr service doesn't appear to work on a public or internal domain name

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/syringe#18]
This needs an Win2008/2012 server on a domain or with a domain name to test, e.g. azure

**Comment by bingnz** [comment]
This is due to the SignalR CORS settings: you need to set the WebsiteUrl setting for the service in its app.config to the external URL for the Website to allow requests from the Website domain to the service. This can be a list so we should extend the config to have both external and internal URLs.
