### ISSUE TITLE
Choco uninstall/install loses config and admin rights

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#182]
- The admin rights are gone for the service user
- Mongodb version needs to be static
- The configs aren't backed up
- websiteconfig.json is lost

**Comment by Workshop2** [comment]
Related to #45

**Comment by yetanotherchris** [comment]
We should use Docker for mongo and ditch the stupid Windows version/chocolately

**Comment by yetanotherchris** [comment]
Will not fix (wait for Docker/.NET Core maturity)
