### ISSUE TITLE
"Available Variables" list improvements

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#185]
Currently the list just gets bigger and bigger. We could do some of the following to improve the experience:

- Display Environment with variables
- Group variables together with name + environment so you can see the different combinations
- Click to copy functionality so you can then use the variable quickly from the clipboard
- Show only top 10(?) and click to expand. Maybe like the TJG homepage?

**Comment by hemdagem** [comment]
What about autocomplete? So if you start typing in the relevant field and it pops up.
