### ISSUE TITLE
Spike: LiteDb

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#188]
- Is it fast enough?
- Easy to configure and manage?

**Comment by yetanotherchris** [comment]
I don't think it's a good idea for the server, but on development machines it makes sense

**Comment by Workshop2** [comment]
@yetanotherchris why not?

**Comment by Workshop2** [comment]
@hemdagem @yetanotherchris simple implementation. Seems really easy to use... might be worth stress testing it?

*Note*: There is some filter logic missing in the test repo for the list pages

**Comment by yetanotherchris** [comment]
Seems snappy. I'll write repository tests in the next few days so we can try it against those.

I would be a bit worried about it being used for multi-users as if the database corrupts that could be a pain in the bum to fix. 

Or perhaps we could hammer it with some soak tests and just use it? I like being able to see the MongoDB data in MongoChef etc.

**Comment by Workshop2** [comment]
@yetanotherchris the only data we store are test results...they seem pretty disposable IMO
