### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by hemdagem** [TotalJobsGroup/Syringe#193]
In the results section the environment text is the same colour as the background so its not visible
![image](https://cloud.githubusercontent.com/assets/8593941/16870424/5f253e64-4a79-11e6-87ab-01a3dfcb1395.png)

In the editor the red line that appears below the available variables should only appear when there is an error.

![image](https://cloud.githubusercontent.com/assets/8593941/16870451/81dd5306-4a79-11e6-85a3-22c0bfc6bc1c.png)

**Comment by yetanotherchris** [comment]
lgtm
