### ISSUE TITLE
Run any particular tests are not redirecting to results page

### ISSUE THREAD

**Issue by rajakm** [TotalJobsGroup/Syringe#194]
Steps to reproduce:
=============
1. Having two test cases in a json file.
2. Choose any particular test and click green icon to run the test.
3. After test is done, it is not redirecting to results page.

If run whole json file, then it shows the results properly.

**Comment by Workshop2** [comment]
@hemdagem @yetanotherchris - can we remove the feature to run an individual test case, I don't think it is very useful and it becomes useless if you depend on captured variables

**Comment by hemdagem** [comment]
Feature should be removed. It's unlikely you will ever do this.

**Comment by Workshop2** [comment]
I will look into removing this on my next train
