### ISSUE TITLE
BLOB/S3/Github Release....assets

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#201]
Hey guys,

At the moment we are deploying assets to Azure blob storage and I was wondering if we could instead publish our artefacts as a Github Release with files.

This would put everything in one place and means we don't have to manage a blob storage instance (etc).

_p.s I do this with Noobot in AppVeyor (built in feature): https://github.com/noobot/SlackConnector/releases_
 
Thanks,
Simon

@yetanotherchris @hemdagem

**Comment by Workshop2** [comment]
Here is an example: https://github.com/TotalJobsGroup/Syringe/releases/tag/1.0.420

Updated this branch: https://github.com/TotalJobsGroup/Syringe/tree/publish-to-github-in-appveyor

We can then hook up the Choco script to pull the latest from here instead of a BLOB/S3 bucket

**Comment by hemdagem** [comment]
@Workshop2 sounds good to me!
