### ISSUE TITLE
Add ability to check all canary pages are running fine before running tests

### ISSUE THREAD

**Issue by hemdagem** [TotalJobsGroup/Syringe#21]

**Comment by hemdagem** [comment]
This isn't essential. we can always create a smoke test file which is ordered first so it will always run first. However if we want it to stop further progress then that's another issue.

**Comment by Workshop2** [comment]
Maybe we should have the ability to create a dependency on another test suite? We could then force that to run first, and only run your selected tests if they pass?

**Comment by yetanotherchris** [comment]
Closing this as I think #132 will solve the problem
