### ISSUE TITLE
Add ability to run run tests against specific environments (not sure this is needed?)

### ISSUE THREAD

**Issue by hemdagem** [TotalJobsGroup/Syringe#22]

**Comment by Workshop2** [comment]
I think this makes sense, otherwise how can you target different teams/individuals boxes?

**Comment by yetanotherchris** [comment]
@workshop2 @hemdagem Big brain dump, this is what I plan to do:

- Users have profiles
- Syringe has a list of environments
- Two EnvironmentProviders: JsonProvider and OctopusProvider. The first gets the environments from a JSON file, the second via the Octopus REST api
- Variables have target environments, just like Octopus
- Variable edit page has another column for environment
- No need for teams as they just complicate things
- User profile stores the user's default environment
- Running a test file asks you for the environment

Any thoughts?

**Comment by hemdagem** [comment]
Sounds good to me.

**Comment by yetanotherchris** [comment]
Environments are in, in JSON format. Moving this to separate issues
