### ISSUE TITLE
Add Git integration for XML files

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#25]
When you save an XML test cases file, it commits and pushes to a Git repository.

It also needs to sync with Git so it always has the latest when editing.

Do we bother with branches per environment or use master? If we use branches, when is master used? Perhaps a config key could map an environment to master.

**Comment by hemdagem** [comment]
We can use branches and the pull request can can be verified by the owner of the master branch. As you say we can add the sync functionality to get latest changes.

**Comment by yetanotherchris** [comment]
We'll need to be able to select the environment when you edit or add an XML
file, and they end up being saved in
d:/syringe/environmentName/50cases.xml.

On Sat, 26 Mar 2016, 15:20 Hemang Rajyaguru, <notifications@github.com>
wrote:

> We can use branches and the pull request can can be verified by the owner
> of the master branch. As you say we can add the sync functionality to get
> latest changes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TotalJobsGroup/syringe/issues/25#issuecomment-201856163>
>
-- 

Sent from my Android

**Comment by yetanotherchris** [comment]
Making branches link to environments doesn't make sense, it's better to
just add all the branches in a config file and make it obvious which branch
of the XML file you're editing or running. We can add the default branch
for a user in their profile.

On Sat, 26 Mar 2016, 17:02 Chris Small, <mrshrinkray@gmail.com> wrote:

> We'll need to be able to select the environment when you edit or add an
> XML file, and they end up being saved in
> d:/syringe/environmentName/50cases.xml.
>
> On Sat, 26 Mar 2016, 15:20 Hemang Rajyaguru, <notifications@github.com>
> wrote:
>
>> We can use branches and the pull request can can be verified by the owner
>> of the master branch. As you say we can add the sync functionality to get
>> latest changes.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/TotalJobsGroup/syringe/issues/25#issuecomment-201856163>
>>
> --
>
> Sent from my Android
>
-- 

Sent from my Android

**Comment by hemdagem** [comment]
yep that sounds good.

**Comment by yetanotherchris** [comment]
Latest group thinking:

- No branching, that's just overkill
- Putting Git integration into Syringe will be a headache for merges, so don't.
  - _(It could be done by writing an IFileHandler that has Git support, and always "take theirs")_
- Maybe have one Git feature in Syringe to `git init` the folder the XML files are stored in
- Look into ways of doing `git pull` via the browser.
- Look into ways of doing `git commit` and `git push` via the browser.
- Are there web UIs for local Git repositories (not Git servers)?

**Comment by yetanotherchris** [comment]
No longer a required feature we can revisit if needed
