### ISSUE TITLE
Upgrade to DotNet Core

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#253]
Let's use this to talk about the issue

**Comment by yetanotherchris** [comment]
1. Keep the seperate Webapi project for the service?
2. Or do we combine them into 1 project MVC/WebApi?

#1 - makes it easier to manage for code maintenance (the runners might need to go into Core).
#2 - configuration is easier, but you'd need two instances running. More IoC setup?

**Comment by Workshop2** [comment]
Which leads me on to my next question: What IOC should we use?

Continue with Structuremap or try something else?

**Comment by yetanotherchris** [comment]
Yes for structuremap for me, here's an example:


	project.json:
	"StructureMap.Microsoft.DependencyInjection": "1.0.1",


	public class Startup
	{
	    public IConfigurationRoot Configuration { get; }

		public Startup(IHostingEnvironment env)
	    {
	        // etc.
	    }

	    // This method gets called by the runtime. Use this method to add services to the container.
	    public void ConfigureServices(IServiceCollection services)
	    {
	        services.AddLogging();
	        services.AddSingleton<MyUserService>();
	        services.AddScoped<MyUserRepository>();
	        services.AddMvc();

			IoC.Container.Populate(services);
	    }
	}

		public static class IoC
		{
			public static Container Container { get; set; }

			static IoC()
			{
				Container = new Container();
			}
		}

**Comment by yetanotherchris** [comment]
Done

🥂 🎆 ✨

**Comment by Workshop2** [comment]
Yay, well done
