### ISSUE TITLE
Regex matching not working correctly

### ISSUE THREAD

**Issue by colmprunty** [TotalJobsGroup/Syringe#258]
Trying to capture a variable using this regex:

`title="hiring organization">.*<h3>.*<a href="(.*)"`

on a page that includes this html

```
<li class="company" property="hiringOrganization" typeof="Organization" title="hiring organization">
<h3>
<a href="https://www.totaljobs.local.tjgdev.ds/jobs-at/totaljobs-testjobload-company-08/jobs" title="Totaljobs TestJobLoad Company 08">Totaljobs TestJobLoad Company 08</a>
<meta property="name" content="Totaljobs TestJobLoad Company 08" />
<meta property="logo" content="https://www.totaljobs.local.tjgdev.ds/companylogos/lucy mobile_124x44(1).jpg" />
</h3>
 </li>
```

It matches way more stuff than it should.

**Comment by Workshop2** [comment]
You might need to work on the regex as it might be too greedy at the moment.

Just been playing and this might work:
``` regex
<li.*?property="hiringOrganization".*?>.|\n*<a.*?href="(\/jobs-at\/.*?\/jobs)".*?">
```

https://regex101.com/r/e688mE/2

**Comment by colmprunty** [comment]
Cool, I'll give it a spin on Monday.

**Comment by Workshop2** [comment]
@colmprunty Does this work?

**Comment by Workshop2** [comment]
@colmprunty I am going to close this issue. If you find it's still not working then let me know

**Comment by hemdagem** [comment]
Colm isn't in. I'll verify it.
