### ISSUE TITLE
Change the confusing webinject naming

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/syringe#26]
The webinject naming is confusing:

- Test case
- Case
- GlobalConfig
- ParsedResponses
Etc.

Maybe borrow XUnit or Nunit's naming, or another testing tool.

**Comment by hemdagem** [comment]
Nunit sounds good:

TestFixture - Test case
Test - case
ParsedResponse needs a rename its too confusing

**Comment by yetanotherchris** [comment]
ParseResponses isn't intuitive, maybe `CapturedVariables` instead

**Comment by yetanotherchris** [comment]
`Verifications` => `Assertions`?

**Comment by hemdagem** [comment]
Should we go ahead with those:

`TestFile` - `TestFixture` 
`TestCase` - `Test`
`ParseResponses` - `CapturedVariables`
`Verifications` - `Assertions`

**Comment by hemdagem** [comment]
This is complete
