### ISSUE TITLE
Remove the ID attribute for a Case

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/syringe#29]
Do you need an ID attribute for a case? Probably not, they seemed to be there originally to order the tests, which means they're not IDs but Order= attributes.

I say remove 'em

**Comment by hemdagem** [comment]
They are currently used for editing individual cases, otherwise we won't be able to tell which case we are editing?

**Comment by yetanotherchris** [comment]
@hemdagem does it break the editor if the ID is missing from the XML? (I'm not sure if the TestCaseReader lets you do that though)

**Comment by hemdagem** [comment]
yep uses it for editing the individual test case. We could alternatively use the index position of the testcase and do it that way.

**Comment by hemdagem** [comment]
This is complete
