### ISSUE TITLE
Remove the sleep attribute

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/syringe#30]
It's not needed, and I don't think ever will be needed?

I can't think of a case where you would need to throttle your HTTP requests unless you are spidering a site - maybe waiting for the web server to perform a background task?

For example the web server might take 3 minutes for your signup to complete.

**Comment by hemdagem** [comment]
Agreed, we aren't doing client tests so I don't see what we would be waiting for. Should be removed.

**Comment by yetanotherchris** [comment]
https://github.com/TotalJobsGroup/syringe/pull/31
