### ISSUE TITLE
Make Syringe easier to upgrade (via Chocolatey)

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#45]
Right now `choco upgrade syringe` blanks out the config files, or fails. Fix!

**Comment by yetanotherchris** [comment]
- Need to blank the MongoDB if there's a schema change

**Comment by yetanotherchris** [comment]
#### Tech notes

- chocolatey argument to keep config files (needs new web.config file=)
- stop app pool first
- stop service first

**Comment by Workshop2** [comment]
@yetanotherchris @hemdagem I have just pushed a change that means you don't need to ```blat``` mongo on a schema change - you need to add an attribute to the model that is missing the old property: ```[BsonIgnoreExtraElements]```

46a7c6a

**Comment by yetanotherchris** [comment]
Will not fix (wait for Docker/.NET Core maturity)
