### ISSUE TITLE
Add user profiles, and a default environment for a user

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#51]
This will require a user profile page, and storing the profile (their OAuth2 ID and environment) in the MongoDB database.

This should be done by adding an action to the REST service and client equivalent.

**Comment by Workshop2** [comment]
@yetanotherchris - is this still high priority?

**Comment by yetanotherchris** [comment]
@Workshop2 we can do a workaround but just setting a cookie when they set their environment, and reading it so it's the default in the drop down list.

It's definitely going to be an annoyance though

**Comment by yetanotherchris** [comment]
Users were removed in version 2 (.NET core)
