### ISSUE TITLE
Add REST API method to run tests synchronously

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#52]
- Run a test file synchronously (i.e. just `Wait()`)
- Return "true" if they succeeded, "false" if not, including a list of test names/ids that failed for the file.

**Comment by Workshop2** [comment]
@yetanotherchris is this done?

**Comment by Workshop2** [comment]
@yetanotherchris - I think I have seen this in the code, can we resolve this?
