### ISSUE TITLE
Test case regexes do not allow HTML

### ISSUE THREAD

**Issue by irmbrady** [TotalJobsGroup/Syringe#57]
For example, adding a <span> to the Regex causes a `A potentially dangerous Request.Form value was detected from the client` error.

Escaping the characters, e.g. `\<span\>` gets the same error.

HTML encoding allows the test to be saved, but then the regex does not match when the test is ran.

**Comment by yetanotherchris** [comment]
Fixed in c2d8596a26d83c2a15abdf4363a3d56d41992335

**Comment by irmbrady** [comment]
Can confirm this is now working correctly.
