### ISSUE TITLE
Add DOM selectors to test cases

### ISSUE THREAD

**Issue by irmbrady** [TotalJobsGroup/Syringe#58]
When adding test cases, instead of only inserting a regex, I would like to be able to add a 'find this value in this element'.

Take the following HTML for example:

```
    <div id="server-status">
        Online
    </div>
```

I would like the assert that `server-status` has the value `Online`.

**Comment by hemdagem** [comment]
@yetanotherchris @irmbrady maybe we don't use regex at all and just use dom selectors like the jquery ones. Much easier to use instead of regex.

**Comment by yetanotherchris** [comment]
We'll need regex when it's not HTML (JSON/XML) or for headers

**Comment by hemdagem** [comment]
yeah good point

**Comment by hemdagem** [comment]
@yetanotherchris anglesharp looks interesting for dom selection https://github.com/AngleSharp/AngleSharp

I think csquery is no longer actively supported.

**Comment by Workshop2** [comment]
AngleSharp is meant to be much faster too

**Comment by yetanotherchris** [comment]
Needs tests coverage to close this - see `CsQueryMatcherTests`

**Comment by yetanotherchris** [comment]
See sizzle for docs
