### ISSUE TITLE
Add 'Run All Tests' button to the View?filename= page

### ISSUE THREAD

**Issue by irmbrady** [TotalJobsGroup/Syringe#59]
I would like to be able to click a 'Run All Tests' button from the `View?filename=` page, instead of having to go back to the 'view all Test Files' page.

**Comment by irmbrady** [comment]
Pressing the run button currently causes errors. It appears that this button does not take the new 'Environment' features into account.

**Comment by hemdagem** [comment]
applied a fix for this, needs to be tested again @irmbrady

**Comment by Workshop2** [comment]
Confimed
