### ISSUE TITLE
Incorrect regex causes error, reason for error is not clear

### ISSUE THREAD

**Issue by irmbrady** [TotalJobsGroup/Syringe#65]
Adding a Test with an invalid regex on the assertion causes the test to error when it runs. It gives the following message `Input string was not in a correct format`.

However, the error message is not clear which input string was invalid, and having multiple assertions makes it harder to debug.

For example, putting `{baseurl}` in the regex field caused the error.

**Comment by hemdagem** [comment]
@irmbrady The logger was crashing and causing this error. Unrelated to the assertions themselves. I have applied a fix for this
