### ISSUE TITLE
Add config option to turn off authentication

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#78]
So you can install syringe locally without needing to login.

 It could maybe just check for empty oauth2 providers and default the user context to the environment.currentuser

**Comment by yetanotherchris** [comment]
Needs verification @hemdagem @Workshop2 

- Remove all your OAuth settings from the service configuration.json
- Start the service (you should be "guest user" there's no way of seeing this though)

**Comment by yetanotherchris** [comment]
Here's an example:

	{
		"ServiceUrl": "http://*:1981",
		"WebsiteUrl": "http://localhost:1980",
		"TestFilesBaseDirectory": "..\\..\\..\\..\\Xml-Examples",
		"ReadonlyMode": false,
		"OAuthConfiguration": {

		}
	}

**Comment by Workshop2** [comment]
Confirmed :+1:
