### ISSUE TITLE
Add config option to disable editing

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#79]
So syringe can be used as a runner only

When turned off, the various edit/delete buttons is disabled along with the mvc edit routes showing 403 HTTP statuses.

**Comment by yetanotherchris** [comment]
Change your service configuration to test this, here's an example:

	{
		"ServiceUrl": "http://*:1981",
		"WebsiteUrl": "http://localhost:1980",
		"TestFilesBaseDirectory": "..\\..\\..\\..\\Xml-Examples",
		"ReadonlyMode": true,
		"OAuthConfiguration": {
		}
	}

**Comment by Workshop2** [comment]
Confirmed
