### ISSUE TITLE
Add a shared-variables.json file and provider

### ISSUE THREAD

**Issue by yetanotherchris** [TotalJobsGroup/Syringe#80]
For variables that are shared among test files. 

The could also encrypt sensitive data using a key in the configuration.json file.

**Comment by Workshop2** [comment]
I am going to focus just on the shared-variables.json

Encryption can come later...

**Comment by Workshop2** [comment]
I am also not going to do a UI - this again can be done later

**Comment by Workshop2** [comment]
This will display all variables when editing tests, but no way to edit it via the UI...which is probably a good thing?
