### ISSUE TITLE
Tagging test files

### ISSUE THREAD

**Issue by Workshop2** [TotalJobsGroup/Syringe#92]
I would like to add tags against tests (e.g. search, apply) so I can run all test files that contain specific tags.

This would allow me to run all tests that touch e.g. search

**Comment by Workshop2** [comment]
https://github.com/aehlke/tag-it

**Comment by Workshop2** [comment]
If we had a pre-determined list of tags, they could also be linked to Smoke tests.

E.g. if a test file had the tag of ```Search```, then it would run the smoke tests for ```Search```

**Comment by yetanotherchris** [comment]
http://welldonethings.com/tags/manager is also good, I use that in Roadkill
